# Generated by Django 5.1.2 on 2025-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
