# Generated by Django 5.1.2 on 2025-04-27 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_organizador_paypal_email_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.organizador')),
            ],
        ),
    ]
