# Generated by Django 5.1.2 on 2025-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='batch_id',
        ),
        migrations.AlterField(
            model_name='payout',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='payout',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
