# Generated by Django 5.1.2 on 2025-04-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_remove_payout_batch_id_alter_payout_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento, ejemplo 20 para 20%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='oferta_activa',
            field=models.BooleanField(default=False),
        ),
    ]
