# Generated by Django 5.1.2 on 2025-04-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_descuento_evento_oferta_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='oferta_activa',
        ),
    ]
