# Generated by Django 5.1.2 on 2025-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('parcial', 'Parcial')], default='pendiente', max_length=20),
        ),
    ]
