# Generated by Django 5.1.2 on 2025-05-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_reembolso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='eventos.pago'),
        ),
    ]
