# Generated by Django 5.1.2 on 2025-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_remove_evento_destacado_pago_ciudad_pago_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='notas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
